spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/cjeditor?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://116.62.238.210:3306/cjeditor?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    #password: root
    password: Jur828Lon920&
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: jurlon.cjeditor.mybatis.model #别名扫描包
  mapper-locations: classpath:mybatis/*.xml #mybatis xml路径
druid:
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  filters: stat,wall,logback
  initialSize: 5
  maxActive: 300
  maxPoolPreparedStatementPerConnectionSize: 20
  maxWait: 60000
  minEvictableIdleTimeMillis: 300000
  minIdle: 10
  poolPreparedStatements: true
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  useGlobalDataSourceStat: true
  validationQuery: SELECT 1 FROM DUAL

