spring:
  redis:
    #host: 116.62.238.210
    host: 192.168.88.128
    password: 
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: 10s
        max-idle: 8
        min-idle: 2
    timeout: 5s
redis-switch:
  NAVIGATION_BAR: ON #开启导航栏缓存
redis-timeout:
  NAVIGATION_BAR: 60 #超时时间 单位:分钟